# Generated by Django 4.1.5 on 2023-01-26 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
