# Generated by Django 4.1.5 on 2023-01-27 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_hotel_average_rating_postimages_comment_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostImages',
        ),
    ]
